#!/usr/bin/env python3
"""Print the part of the release notes CI is responsible for.

The release is created as a draft with this as its body; the human written
notes (one opening paragraph and "What's new") go above the marker. The
generated part is the download and install guide, one section per operating
system with a direct link, and the "checking for updates" note at the end.

The checksum of every download is embedded as an HTML comment. The in-app
updater reads the zip's checksum from there (ReleaseChecksum.h), so nothing
has to be attached to the release beside the downloads themselves.

Usage: write-release-body.py <version> <owner/repo> <checksums-file>
  checksums-file: `sha256sum` output, one "<hex>  <file>" line per download
"""

import sys

TEMPLATE = """<!--
  Release notes go above this comment, in this order:
    1. one paragraph: what this release is
    2. ## What's new
  Everything below is generated by CI. Leave it in place.
-->

## Download and install

Pick the one for your computer. You only ever need one file.

### Windows

Download **[PortalLauncher-Setup-{version}.exe]({base}/PortalLauncher-Setup-{version}.exe)** and run it. Windows may show a blue "Windows protected your PC" box the first time because the installer is not code signed yet: click "More info", then "Run anyway". Any Prism Launcher instances and accounts you already have are picked up automatically.

The [PortalLauncher-Windows-MSVC-{version}.zip]({base}/PortalLauncher-Windows-MSVC-{version}.zip) is what the launcher's built-in updater downloads. You do not need it unless you want to unpack the launcher somewhere yourself.

### macOS

Download **[PortalLauncher-macOS-{version}.dmg]({base}/PortalLauncher-macOS-{version}.dmg)**, open it and drag Portal Launcher into Applications. It runs on Apple silicon and Intel Macs, macOS 12 or newer. The first time you open it macOS will say it cannot check the app for malware: close that message, open System Settings, go to Privacy & Security, scroll down and click "Open Anyway" next to Portal Launcher. On macOS 14 and older, right click the app and choose Open instead. You only have to do this once.

### Linux

Download **[PortalLauncher-Linux-x86_64.AppImage]({base}/PortalLauncher-Linux-x86_64.AppImage)**, mark it executable (`chmod +x PortalLauncher-Linux-x86_64.AppImage`) and run it.

## Checking for updates

Windows installs update themselves: the launcher checks once a day, or use Help > Check for Updates any time. Settings, instances and accounts all carry over. On macOS and Linux, download the new file from the newest release when one comes out; your settings and instances stay where they are.

<!--
{checksums}
-->
"""


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    version, repo, checksums_path = sys.argv[1:4]
    base = f"https://github.com/{repo}/releases/download/{version}"
    lines = []
    with open(checksums_path, encoding="utf-8") as handle:
        for raw in handle:
            parts = raw.split()
            if len(parts) >= 2:
                lines.append(f"sha256 {parts[1].lstrip('*')} {parts[0].lower()}")
    if not lines:
        print("::error::No checksums to embed in the release body", file=sys.stderr)
        return 1
    sys.stdout.write(TEMPLATE.format(version=version, base=base, checksums="\n".join(lines)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
