#!/usr/bin/env python3
"""Print the part of the release notes CI is responsible for.

The release is created as a draft with this as its body; the human written
notes go above the marker. Keeping the provenance section generated means every
release says where its binaries came from and how to check them, with the right
commit and version filled in, without anyone having to remember.

Usage: write-release-body.py <version> <commit> <owner/repo>
"""

import sys

TEMPLATE = """<!--
  Release notes go above this comment, in this order:
    1. one paragraph: what this release is, and how a new user installs it
    2. ## What's new
    3. ## Updating from an older build
  Everything below is generated by CI. Leave it in place.
-->

## Where these files come from

Every file here was built by GitHub Actions from commit `{commit}` of this repository, not on anyone's personal machine. The workflow that built it is public, and so is the run, so you can read exactly what produced each download.

Each file also carries a signed build provenance attestation. With the [GitHub CLI](https://cli.github.com) you can confirm a download really is the file this repository built:

```
gh attestation verify PortalLauncher-Setup-{version}.exe --repo {repo}
```

That works for any file attached to this release (the Windows installer and zip, the macOS disk image, the Linux AppImage), so put in the name of whichever one you downloaded. If you only want to know the download is not corrupted, every file has a `.sha256` beside it.

Windows builds are not code signed yet, so SmartScreen may warn the first time you run one: click "More info", then "Run anyway". Verifying the attestation above is a stronger check than a signature would be.

The macOS build (one app for Apple silicon and Intel) is not notarized with Apple yet either. The first time you open it macOS will say it cannot check it for malware: close that message, open System Settings, go to Privacy & Security, scroll down and click "Open Anyway" next to Portal Launcher. On macOS 14 and older, right click the app and choose Open instead. You only have to do this once.
"""


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    version, commit, repo = sys.argv[1:4]
    sys.stdout.write(TEMPLATE.format(version=version, commit=commit, repo=repo))
    return 0


if __name__ == "__main__":
    sys.exit(main())
